# alias
alias ls='ls --color=auto'
alias ll='ls -alF --color=auto'
alias 'vi=vim'
alias 'cdwork=cd ~/Work'
alias 'cdxiron=cd ~/Work/project/xiron'
alias 'cdmotie=cd ~/Work/project/motie'
alias 'cdgit=cd ~/Github'
alias 'cdblog=cd ~/git/liang/codingted.github.io'
alias 'cddatax=cd ~/work/project/tushu/DataX'
alias 'vi3c=vi ~/.config/i3/config'
alias rm="trash"
alias RM="trash"
alias trash-rm="/bin/rm -rf $HOME/.local/share/Trash/files/"
alias rm-trash="/bin/rm -rf $HOME/.local/share/Trash/files/"
alias rm-trash-root="/bin/rm -rf /root/.local/share/Trash/files/"

alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.cnpmrc"

alias mci="mvn clean install"

alias pbcopy="xclip -selection clipboard"
alias pbpaste="xclip -selection clipboard -o"

alias setproxy="export ALL_PROXY=socks5://127.0.0.1:1087"
alias unsetproxy="unset ALL_PROXY"

alias sshproxy="ssh -D 1087 -o ServerAliveInterval=60 root@108.61.247.137"

alias motielog="/home/zl/Script/motie/motie_watch_log.sh"
alias xironlog="/home/zl/Script/motie/xiron_watch_log.sh"

alias zkstart="sudo /home/zl/Tools/zookeeper-3.4.14/bin/zkServer.sh start-foreground"
