# alias
alias 'cdwork=cd ~/work'
alias 'cdgit=cd ~/git'
alias 'cdblog=cd ~/git/liang/codingted.github.io'
alias 'cddatax=cd ~/work/project/tushu/DataX'
alias rm="trash"
alias RM="trash"
alias trash-rm="/bin/rm -rf $HOME/.local/share/Trash/files/"
alias rm-trash="/bin/rm -rf $HOME/.local/share/Trash/files/"
alias rm-trash-root="/bin/rm -rf /root/.local/share/Trash/files/"
