#
# ~/.bashrc
#
echo "~/.bashrc"
[[ -f ~/.bash_alias ]] && . ~/.bash_alias
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '
PS1="$PS1\$(git status 2>/dev/null | grep 'On branch' | sed 's/On branch / => /') $ "

# history search
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# 
export HISTCONTROL=ignoredups

complete -c man which
