#
# ~/.bashrc
#
echo "~/.bashrc"
[[ -f ~/.bash_alias ]] && . ~/.bash_alias
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Git branch in prompt.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

PS1='\e[0;32m[\u@\h \W]\e[m '
PS1="$PS1\$\e[0;31m\$(parse_git_branch)\e[m "

# history search
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# PATH
PATH="$PATH:/home/zl/.local/bin"
export PATH
